[package]
name = "beamplot"
version = "0.1.0"
edition = "2021"
authors = ["Berke DURAK <bd@exhrd.fr>"]
license = "MIT OR APACHE-2.0"
readme = "README.md"
description = "Plotter"
repository = "https://github.com/berke/beamplot"

[dependencies]
beambook = { path = "../book" }